export interface Visitas {
VisitaID?:string,
assigned_user_id?:string,
CodUsuario?:string,
zona_instalacion?:string,
cliente?:string,
billing_address_street?:string,
phone_office?:string,
Ot?:string,
telefono_contacto?:string,
DivisionID?:string,
RegionalID?:string,
AmercadoID?:string, 
fecha_visita_c ?:string,
fecha_final_plan?:string,
fecha_final_real?:string,
fecha_inicio_plan?:string,
fecha_inicio_real?:string,
Estado?:string,
tiposinstalaciones?:string,
latitud_plan?:string,
longitud_plan?:string,
latitud_real?:string,
longitud_real?:string,
description?:string,
Cuadrilla?:string
}
